services:
  - type: web
    name: freshers-2026-portal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
